# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Azure Function App (staging slot)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write        # for OIDC‐based login
      contents: read         # for checkout

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # ──────────────────────────────────────────────────────────────────────────
      # 1) Publish *only* the Functions project into ./publish
      - name: Publish Functions project
        run: |
          dotnet publish src/Functions/Functions.csproj --configuration Release --output publish

      # ──────────────────────────────────────────────────────────────────────────
      # 2) Authenticate to Azure via OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_595A7BCF57C7446ABAA95687052520AB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E65A540DCA2D41A2A2CEDF5C9C52DA3D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2E778669D9CA4A579827736C0A7C303B }}

      # ──────────────────────────────────────────────────────────────────────────
      # 3) Deploy to your Function App’s staging slot
      - name: Deploy to Azure Functions (staging slot)
        uses: azure/functions-action@v1
        with:
          app-name:  saivagentapi    # <— your Function App name, *not* saivagentapi/staging
          slot-name: staging         # <— the slot you created in Azure
          package:   publish         # <— the folder we just published into

      # ──────────────────────────────────────────────────────────────────────────
      # 4) (Optional) Post‐deployment slot‐swap
      # - name: Swap staging to production
      #   run: |
      #     az functionapp deployment slot swap \
      #       --name saivagentapi \
      #       --resource-group g8-hackathongroup \
      #       --slot staging \
      #       --target-slot production

          
